# Generated by Django 6.0.2 on 2026-02-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docrobot_id', models.CharField(max_length=100, unique=True, verbose_name='ID в Docrobot')),
                ('doc_type', models.CharField(choices=[('ORDER', 'Заказ'), ('ORDRSP', 'Подтверждение заказа'), ('DESADV', 'Уведомление об отгрузке'), ('INVOICE', 'Счёт-фактура'), ('PRICAT', 'Прайс-лист')], max_length=10, verbose_name='Тип')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('supplier_gln', models.CharField(blank=True, max_length=13, verbose_name='GLN поставщика')),
                ('buyer_gln', models.CharField(blank=True, max_length=13, verbose_name='GLN покупателя')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('buyer_name', models.CharField(blank=True, max_length=255, verbose_name='Покупатель')),
                ('raw_json', models.JSONField(default=dict, verbose_name='Сырые данные JSON')),
                ('xml_content', models.TextField(blank=True, verbose_name='Сгенерированный XML')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
            ],
            options={
                'verbose_name': 'EDI-документ',
                'verbose_name_plural': 'EDI-документы',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='XmlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ORDER', 'Заказ (ORDER)'), ('ORDRSP', 'Подтверждение (ORDRSP)'), ('DESADV', 'Отгрузка (DESADV)'), ('INVOICE', 'Счёт-фактура (INVOICE)'), ('PRICAT', 'Прайс-лист (PRICAT)')], max_length=10, unique=True, verbose_name='Тип документа')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('position_tpl', models.TextField(blank=True, help_text='Переменные: {{line}}, {{ean}}, {{item_code}}, {{item_name}}, {{quantity}}, {{unit_price}}, {{vat}}, {{amount}}, {{amount_with_vat}}', verbose_name='Шаблон позиции')),
                ('body_tpl', models.TextField(help_text='Используйте {{переменная}} для подстановки данных.', verbose_name='Шаблон документа (XML)')),
                ('content_type', models.CharField(default='application/xml; charset=utf-8', max_length=60, verbose_name='Content-Type для 1С')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'XML-шаблон',
                'verbose_name_plural': 'XML-шаблоны',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=5, verbose_name='Уровень')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='edi.edidocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('sent', 'Отправлен'), ('error', 'Ошибка (повтор)'), ('failed', 'Не удалось отправить')], default='pending', max_length=10, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('response', models.TextField(blank=True, verbose_name='Ответ 1С')),
                ('http_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в 1С')),
                ('next_retry', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='edi.edidocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Запись очереди',
                'verbose_name_plural': 'Очередь отправки',
                'ordering': ['-created_at'],
            },
        ),
    ]
