# Generated by Django 6.0.2 on 2026-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsettings',
            name='docrobot_gln',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='GLN компании'),
        ),
    ]
