# Generated by Django 6.0.2 on 2026-02-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='connectionsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sendqueue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xmltemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='cleanup_days',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='docrobot_gln',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='docrobot_poll_interval',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='onec_password',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='onec_timeout',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='onec_username',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='documentcomment',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='documentcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sendqueue',
            name='next_retry',
        ),
        migrations.RemoveField(
            model_name='xmltemplate',
            name='content_type',
        ),
        migrations.AddField(
            model_name='edidocument',
            name='api_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус API (unread/read)'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='doc_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус документа'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='docflow_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID цепочки (v3)'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='sign_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписать до'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='edi.edidocument'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='level',
            field=models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=5),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_url',
            field=models.CharField(default='https://edi-api.docrobot.kz', max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edi.edidocument'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='raw_json',
            field=models.JSONField(default=dict, verbose_name='Сырой JSON'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='xml_content',
            field=models.TextField(blank=True, verbose_name='XML для 1С'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='edi.edidocument'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправка'), ('sent', 'Отправлен'), ('error', 'Ошибка'), ('failed', 'Провал')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='body_tpl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='doc_type',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='position_tpl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
