# Generated by Django 6.0.2 on 2026-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0002_add_gln_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsettings',
            name='cleanup_days',
            field=models.IntegerField(default=90, verbose_name='Хранить документы (дней, 0 = не удалять)'),
        ),
    ]
