# Generated by Django 6.0.2 on 2026-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0002_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edidocument',
            name='sign_till',
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='importance',
            field=models.CharField(choices=[('normal', 'Обычный'), ('warn', 'Внимание'), ('urgent', 'Срочно')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='api_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус API'),
        ),
    ]
