# Generated by Django 6.0.2 on 2026-02-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0003_remove_edidocument_sign_till_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='connectionsettings',
            options={'verbose_name': 'Настройки подключений', 'verbose_name_plural': 'Настройки подключений'},
        ),
        migrations.AlterModelOptions(
            name='documentcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='sendqueue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись очереди', 'verbose_name_plural': 'Очередь отправки'},
        ),
        migrations.AlterModelOptions(
            name='xmltemplate',
            options={'verbose_name': 'XML-шаблон', 'verbose_name_plural': 'XML-шаблоны'},
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='cleanup_days',
            field=models.IntegerField(default=90, verbose_name='Хранить документы (дней, 0 = не удалять)'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='docrobot_gln',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='GLN компании'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='docrobot_poll_interval',
            field=models.IntegerField(default=60, verbose_name='Интервал опроса (сек)'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='onec_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль 1С'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='onec_timeout',
            field=models.IntegerField(default=30, verbose_name='Таймаут 1С (сек)'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='onec_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин 1С'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='poll_only_unread',
            field=models.BooleanField(default=True, verbose_name='Только непрочитанные (apiStatus=unread)'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='poll_page_size',
            field=models.IntegerField(default=100, help_text='Рекомендуется 50-100', verbose_name='Документов за запрос'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='connectionsettings',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='marked_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отмечен прочитанным'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='sign_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписать до'),
        ),
        migrations.AddField(
            model_name='edidocument',
            name='timer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Таймер подписания'),
        ),
        migrations.AddField(
            model_name='sendqueue',
            name='next_retry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка'),
        ),
        migrations.AddField(
            model_name='xmltemplate',
            name='content_type',
            field=models.CharField(default='application/xml; charset=utf-8', max_length=60, verbose_name='Content-Type для 1С'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='edi.edidocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='level',
            field=models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=5, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль Docrobot'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_status',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Статус Docrobot'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_tested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверен Docrobot'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_url',
            field=models.CharField(default='https://edi-api.docrobot.kz', max_length=255, verbose_name='URL Docrobot API'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин Docrobot'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_status',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Статус 1С'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_tested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверен 1С'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_url',
            field=models.CharField(default='http://localhost/hs/docrobot/orders', max_length=255, verbose_name='URL 1С HTTP-сервиса'),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edi.edidocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='importance',
            field=models.CharField(choices=[('normal', 'Обычный'), ('warn', 'Внимание'), ('urgent', 'Срочно')], default='normal', max_length=10, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='api_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Статус API (apiStatus)'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='doc_status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Статус прочтения (docStatus)'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='docflow_id',
            field=models.CharField(blank=True, max_length=36, verbose_name='ID цепочки (docflowId)'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='raw_json',
            field=models.JSONField(default=dict, verbose_name='Сырые данные JSON'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='xml_content',
            field=models.TextField(blank=True, verbose_name='Сгенерированный XML'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Попыток'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='edi.edidocument', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP-код'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в 1С'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sending', 'Отправляется'), ('sent', 'Отправлен'), ('error', 'Ошибка (повтор)'), ('failed', 'Не удалось отправить')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='body_tpl',
            field=models.TextField(help_text='Используйте {{переменная}} для подстановки данных.', verbose_name='Шаблон документа (XML)'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='doc_type',
            field=models.CharField(choices=[('ORDER', 'Заказ (ORDER)'), ('ORDRSP', 'Подтверждение (ORDRSP)'), ('DESADV', 'Отгрузка (DESADV)'), ('INVOICE', 'Счёт-фактура (INVOICE)'), ('PRICAT', 'Прайс-лист (PRICAT)')], max_length=10, unique=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='position_tpl',
            field=models.TextField(blank=True, help_text='Переменные: {{line}}, {{ean}}, {{item_code}}, {{item_name}}, {{quantity}}, {{unit_price}}, {{vat}}, {{amount}}, {{amount_with_vat}}', verbose_name='Шаблон позиции'),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='edi_activit_action_aa3579_idx'),
        ),
        migrations.AddIndex(
            model_name='edidocument',
            index=models.Index(fields=['docflow_id'], name='edi_edidocu_docflow_38258f_idx'),
        ),
        migrations.AddIndex(
            model_name='edidocument',
            index=models.Index(fields=['api_status'], name='edi_edidocu_api_sta_e19f77_idx'),
        ),
        migrations.AddIndex(
            model_name='edidocument',
            index=models.Index(fields=['doc_type', 'received_at'], name='edi_edidocu_doc_typ_1fc977_idx'),
        ),
    ]
