# Generated by Django 6.0.2 on 2026-02-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edi', '0004_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='connectionsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentcomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='edidocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sendqueue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xmltemplate',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='edi_activit_action_aa3579_idx',
        ),
        migrations.RemoveIndex(
            model_name='edidocument',
            name='edi_edidocu_docflow_38258f_idx',
        ),
        migrations.RemoveIndex(
            model_name='edidocument',
            name='edi_edidocu_api_sta_e19f77_idx',
        ),
        migrations.RemoveIndex(
            model_name='edidocument',
            name='edi_edidocu_doc_typ_1fc977_idx',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='docrobot_poll_interval',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='onec_timeout',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='poll_only_unread',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='poll_page_size',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='connectionsettings',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='documentcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='xmltemplate',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='level',
            field=models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='cleanup_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_gln',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_url',
            field=models.CharField(default='https://edi-api.docrobot.kz', max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='docrobot_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='onec_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectionsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edi.edidocument'),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='importance',
            field=models.CharField(choices=[('normal', 'Обычный'), ('warn', 'Внимание'), ('urgent', 'Срочно')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='api_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус API'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='doc_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='docflow_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID цепочки'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='raw_json',
            field=models.JSONField(default=dict, verbose_name='JSON из Docrobot'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='sign_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок подписания'),
        ),
        migrations.AlterField(
            model_name='edidocument',
            name='timer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Таймер'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='edi.edidocument'),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='http_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='next_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('sent', 'Отправлен'), ('failed', 'Ошибка'), ('error', 'Системная ошибка')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sendqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='body_tpl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='doc_type',
            field=models.CharField(choices=[('ORDER', 'Заказ'), ('ORDRSP', 'Подтверждение заказа'), ('DESADV', 'Уведомление об отгрузке'), ('INVOICE', 'Счёт-фактура'), ('PRICAT', 'Прайс-лист')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='name',
            field=models.CharField(default='Пользовательский шаблон', max_length=100),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='position_tpl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmltemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='document',
        ),
    ]
